# @package agent
_target_: agent.sac.SACAgent
name: sac
reward_free: ${reward_free}
obs_type: ??? # to be specified later
obs_shape: ??? # to be specified later
action_shape: ??? # to be specified later
device: ${device}
lr: 1e-4
actor_lr: 1e-4
critic_lr: 1e-4
critic_target_tau: 0.005
update_every_steps: 2
use_tb: ${use_tb}
use_wandb: ${use_wandb}
num_expl_steps: ??? # to be specified later
hidden_dim: 1024
feature_dim: 50
stddev_schedule: 0.2
stddev_clip: 0.3
nstep: 3
batch_size: 1024 # 256 for pixels
init_critic: true
learnable_temperature: false
init_temperature: 0.1
actor_update_frequency: 1 
critic_target_update_frequency: 2